name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: |
          docker build . -t titproger/chat_service:latest
      - name: push image to docker hub
        run: |
          docker login -u titproger -p ${{secrets.DOCKER_HUB_TOKEN}}
           docker push titproger/chat_service:latest

  connect_vps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute deploy script on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.VPS_SSH_KEY }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'cd /home/tit/pasim && ./deploy.sh'

